version: '3'
services:
  postgres:
    image: postgres:11.7-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
    volumes:
      - .cache/:/var/lib/postgresql/data
    command: postgres -c log_statement=all -c wal_level=replica
  moon:
    build: .
    ports:
      - "80:80"
    links:
      - postgres
    environment:
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_HOST=postgres:5432
      - DB_NAME=$DB_NAME
